### ISSUE TITLE
Git history rewritten

### ISSUE THREAD

**Issue by LoganDark** [tmpim/kristforge#5]
Did you seriously force-push to this repository and not upload a backup anywhere?

I was looking for a GPU miner, and this seemed like the right choice, but right now it's fucked over.

Do you have any backup copies or anything like that I could use?

**Comment by LoganDark** [comment]
Nevermind, apparently there is no README or anything instructing that everything's on the legacy branch. Stupid me.

**Comment by dmarcuse** [comment]
For future reference taking such an aggressive stance isn't a great way to get people to help you.

**Comment by LoganDark** [comment]
Can you tell me how I'm being aggressive? Everyone's been telling me I've been being aggressive lately, but I'm not sure why.

**Comment by dmarcuse** [comment]
1. Immediately accusing me of sabotaging my own work

2. Using unnecessary profanity

3. Writing in a very entitled way

**Comment by LoganDark** [comment]
1. Well, it sure seemed that way at first.
2. A lot of things are unnecessary... I don't think one swear word should be a reason for calling me aggressive.
3. Entitled? To what? I simply wanted to recover the old version, which I did not know was on another branch. I just forgot to check.

**Comment by dmarcuse** [comment]
Your first sentence was accusing me of overwriting the repository (implying that I did so intentionally to make it more difficult for others). You then explained how "it's fucked over", rather than phrasing this in a more polite manner. Finally, you closed by asking whether I had a backup copy, admittedly in a relatively neutral way (but this doesn't really help given the rude previous sentences).

Here's an example of how you could have written your question:

"Hi, I've been looking for a GPU miner, and kristforge sounded like the right choice. However, it seems that the code is missing from the repository. If this is intentional, could you please show me where I could find the original version? Thank you!"

Note the usage of a more friendly, conversational tone, consideration that this change may not have been to intentionally spite others, and display of gratitude using "please" and "thank you".

**Comment by LoganDark** [comment]
Sorry then, for being 'aggressive'.

**Comment by dmarcuse** [comment]
Even now your comments convey sarcasm and/or indignance. Either way, this isn't the place for this.
